version: '3.8'

services:
  monitoring:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/app  # Mount the current directory to /app in the container

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
